# BASIC LINEAR ALGEBRA EXERCISES IN PYTHON
### Week 1: Exercise 1 - Matrix Multiplication 

In [2]:
import numpy as np

In [6]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print("Matrix of A:")
print(a)
print("Matrix of B:")
print(b)
print("Multiplication(A,B):")
print(c)

Matrix of A:
[[1 2]
 [3 4]]
Matrix of B:
[[5 6]
 [7 8]]
Multiplication(A,B):
[[19 22]
 [43 50]]


### Excercise:2-Eigen Decomposition

In [22]:
A=np.array([[4,2],[1,3]])
eigenvalues,eigenvectors=np.linalg.eig(A)
print(A)
print(eigenvalues)
print(eigenvectors)

[[4 2]
 [1 3]]
[5. 2.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### Exercise 3- Singular Value Decomposition (SVD) 

In [23]:
A=np.array([[3,2,2],[2,3,-2]])
U,S,V=np.linalg.svd(A)
print(A)
print(U)
print(S)
print(V)

[[ 3  2  2]
 [ 2  3 -2]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[5. 3.]
[[ 7.07106781e-01  7.07106781e-01  3.67439059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


### Exercise 4- Determinant Calculation

In [24]:
 A = np.array([[6, 1], [2, 3]]) 
 det = np.linalg.det(A) 
 print("Matrix A:") 
 print(A) 
 print("Determinant of A:") 
 print(det) 

Matrix A:
[[6 1]
 [2 3]]
Determinant of A:
15.999999999999998


### Exercise 5 - Norm Calculation

In [29]:
V=np.array([3,4])
l1_norm=np.linalg.norm(V,ord=1)
l2_norm=np.linalg.norm(V)
print(V)
print(l1_norm)
print(l2_norm)

[3 4]
7.0
5.0
