In [2]:
import numpy as np
A=np.array([[4,2],[1,3]])
eigenvalues,eigenvectors=np.linalg.eig(A)
print("Matrix of A:")
print(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Matrix of A:
[[4 2]
 [1 3]]
Eigenvalues:
[5. 2.]
Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [4]:
import numpy as np
A=np.array([[4,2,5],[1,3,7]])
eigenvalues,eigenvectors=np.linalg.eig(A)
print("Matrix of A:")
print(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

LinAlgError: Last 2 dimensions of the array must be square

In [5]:
import numpy as np
A=np.array([[4,2,5,7],[1,3,7,8],[1,3,5,6],[1,2,4,5]])
eigenvalues,eigenvectors=np.linalg.eig(A)
print("Matrix of A:")
print(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Matrix of A:
[[4 2 5 7]
 [1 3 7 8]
 [1 3 5 6]
 [1 2 4 5]]
Eigenvalues:
[14.71039501  2.84657881 -0.69451448  0.13754067]
Eigenvectors:
[[ 0.56412043  0.96657812 -0.12478539 -0.27947524]
 [ 0.57621905 -0.22176462 -0.851001   -0.21202103]
 [ 0.4632566  -0.1285715   0.50880841 -0.64704363]
 [ 0.3676045  -0.00406928 -0.03660474  0.67696028]]
