In [2]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=np.dot(A,B)
print(A)
print(B)
print(C)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [15]:
import numpy as np
A=np.array([[2,3],[0,2],[1,2]])
B=np.array([3,3])
C=np.dot(A,B)
print(A)
print(B)
print(C)

[[2 3]
 [0 2]
 [1 2]]
[3 3]
[15  6  9]


In [17]:
import numpy as np
A=np.array([[1,2,3],[3,4,6]])
B=np.array([[5,6],[7,8],[2,6]])
C=np.dot(A,B)
print(A)
print(B)
print(C)

[[1 2 3]
 [3 4 6]]
[[5 6]
 [7 8]
 [2 6]]
[[25 40]
 [55 86]]
