# Singular value Decomposition

In [8]:
import numpy as np 
a=np.array([[3,2,2],[2,3,-2]])
U,S,V=np.linalg.svd(a)
print(a)
print(U)
print(S)
print(V)

[[ 3  2  2]
 [ 2  3 -2]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[5. 3.]
[[ 7.07106781e-01  7.07106781e-01  3.67439059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


In [10]:
import numpy as np 
a=np.array([[3,2],[2,-2]])
U,S,V=np.linalg.svd(a)
print(a)
print(U)
print(S)
print(V)

[[ 3  2]
 [ 2 -2]]
[[-0.94362832 -0.33100694]
 [-0.33100694  0.94362832]]
[3.70156212 2.70156212]
[[-0.94362832 -0.33100694]
 [ 0.33100694 -0.94362832]]


# Determinant Calculation

In [12]:
import numpy as np
A=np.array([[6,1],[2,3]])
det=np.linalg.det(A)
print(A)
print(det)

[[6 1]
 [2 3]]
15.999999999999998


In [19]:
import numpy as np 
A=np.array([[4,5,4],[5,3,5]])
det=np.linalg.det(A)
print(A)
print(det)

LinAlgError: Last 2 dimensions of the array must be square

In [22]:
import numpy as np
A=np.array([[2,3,4],[2,9,6],[4,6,7]])
det=np.linalg.det(A)
print(A)
print(det)

[[2 3 4]
 [2 9 6]
 [4 6 7]]
-11.999999999999995


# Norm Calculation

In [30]:
import numpy as np
V=np.array([3,4])
L1_norm=np.linalg.norm(V,ord=1)
L2_norm=np.linalg.norm(V)
print(V)
print(L1_norm)
print(L2_norm)

[3 4]
7.0
5.0


In [33]:
import numpy as np
V=np.array([3,4,5])
L1_norm=np.linalg.norm(V,ord=1)
L2_norm=np.linalg.norm(V)
print(V)
print(L1_norm)
print(L2_norm)

[3 4 5]
12.0
7.0710678118654755
